name: Test build image
on:
  push:
    branches:
      - master

env:
  # Golang version to use across CI steps
  GOLANG_VERSION: '1.16.5'

jobs:
  build-docker:
    name: Build Docker image
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Build Docker image
        with:
          arch: armv7
          distro: ubuntu18.04
          install: |
            apt-get update
            apt-get install build-essential git curl -y
            curl -O https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz
            tar xvf go1.10.3.linux-amd64.tar.gz
            chown -R root:root ./go
            mv go /usr/local

          run: |
            echo $(uname -a)
            make image